# MPIexperimentUsingNumpy

## [MPI for Python](https://mpi4py.readthedocs.io/en/stable/tutorial.html#collective-communication)


SEE ALSO [Parallel Programming for Science and Engineering](https://web.corral.tacc.utexas.edu/CompEdu/pdf/pcse/EijkhoutParallelProgramming.pdf) from second "! Tip" in "MPI for Python" above

about **Bcast** see also https://www.open-mpi.org/doc/v4.1/man3/MPI_Bcast.3.php with "Broadcasts a message from the process with rank root to all other processes of the group."


In [1]:
%%javascript
// to avoid scroll in windows
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

<IPython.core.display.Javascript object>

In [2]:
%%writefile MPIexperimentUsingNumpy.py

# https://mpi4py.readthedocs.io/en/stable/tutorial.html#collective-communication "Broadcasting a NumPy array"

from mpi4py import MPI
import numpy as np
import time

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
rankNum=comm.Get_size()

data=[0]*rankNum

for k in range(rankNum):
    
    if rank == k:
        data[k]=np.array([np.arange(10*k+1,10*k+11),[k]*10] ,dtype='f')
    else:
        data[k]=np.empty([2,10],dtype='f')

    comm.Bcast(data[k], root=k)
    
    print(time.time(),"rank", rank,"\n",data[k],flush=True)

Overwriting MPIexperimentUsingNumpy.py


In [3]:
# R U N
! mpirun -n 3 python3 MPIexperimentUsingNumpy.py

1663600440.436207 rank 0 
 [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
1663600440.43623 rank 1 
 [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
1663600440.436247 rank 2 
 [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
1663600440.43711 rank 0 
 [[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
1663600440.4371169 rank 1 
 [[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
1663600440.4406772 rank 2 
 [[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
1663600440.441906 rank 2 
 [[21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]
1663600440.441909 rank 0 
 [[21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]
1663600440.441919 rank 1 
 [[21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
 [ 2.  2.  2.  2. 